In [2]:
import gym
import gym_mod_cartpole
from random import random, randint, uniform
from env.decom_lunar_lander import LunarLander as LunarLander_decom_reward
from copy import deepcopy
import os
import torch
import numpy as np
from tqdm import tqdm

from GVF_learner import GVF_learner
from memory.memory import ReplayBuffer_decom
from models.dqn_model import DQNModel

FloatTensor = torch.cuda.FloatTensor
LongTensor = torch.cuda.LongTensor

# Writer = SummaryWriter(log_dir="CartPole_summary")

In [3]:
ENV_NAME = 'test_grid'
ACTION_DICT = {
    "LEFT":0,
    "RIGHT":1
}

In [4]:
# Set result saveing floder
result_floder = ENV_NAME
result_file = ENV_NAME + "/results.txt"
if not os.path.isdir(result_floder):
    os.mkdir(result_floder)

## GVF learner
Train GVF model base on the dataset and policy above

In [5]:
test_GVF_PARAMETERS = {
    "batch size" : 3, # update batch size
    "learning rate" : 0.0001,
    "feature num" : 2, # numbers/length of feature
    "state length" : 4,
    "discount factor" : [0.99], # for each features respectively
    "action space": 4,
    'model_replace_freq' : 10,
    'soft_tau': 0.001
}
def policy(state_actions):
    return 1

def get_dataset():
    dataset = [
        [[1, 0, 0, 0, 1, 0, 0, 0], -1, -1, [1, 0, 0, 0], 0, [-1, 0]],
        [[1, 0, 0, 0, 0, 1, 0, 0], -1, -1, [0, 1, 0, 0], 0, [-1, 0]],
        [[0, 1, 0, 0, 1, 0, 0, 0], -1, -1, [1, 0, 0, 0], 0, [-1, 0]],
        [[0, 1, 0, 0, 0, 1, 0, 0], -1, -1, [0, 0, 1, 0], 0, [-1, 0]],
        [[0, 0, 1, 0, 1, 0, 0, 0], -1, -1, [0, 1, 0, 0], 0, [-1, 0]],
        [[0, 0, 1, 0, 0, 1, 0, 0], -1, -1, [0, 0, 0, 1], 1, [-1, 0]],
        
        [[1, 0, 0, 0, 0, 0, 1, 0], -1, -1, [1, 0, 0, 0], 0, [-1, 0]],
        [[1, 0, 0, 0, 0, 0, 0, 1], -1, -1, [1, 0, 0, 0], 0, [-1, 0]],
        [[0, 1, 0, 0, 0, 0, 0, 0], -1, -1, [0, 1, 0, 0], 0, [-1, 0]],
        [[0, 1, 0, 0, 0, 0, 0, 0], -1, -1, [0, 1, 0, 0], 0, [-1, 0]],
        [[0, 0, 1, 0, 0, 0, 0, 0], -1, -1, [0, 0, 1, 0], 0, [-1, 0]],
        [[0, 0, 1, 0, 0, 0, 0, 0], -1, -1, [0, 0, 1, 0], 0, [-1, 0]],
    ]
    return dataset
        


In [6]:
dataset = get_dataset()
gvf_learner = GVF_learner(test_GVF_PARAMETERS, dataset, policy)
gvf_learner.learn_and_eval(1000, 10)

  2%|▏         | 15/1000 [00:00<01:13, 13.40it/s]

train loss : 0.3661818876862526
train loss : 0.48578018695116043
train loss : 0.6092327684164047


  6%|▌         | 57/1000 [00:00<00:28, 32.86it/s]

train loss : 0.787784032523632
train loss : 0.8037081807851791
train loss : 0.6885520219802856


  8%|▊         | 85/1000 [00:00<00:17, 53.62it/s]

train loss : 0.490154015365988
train loss : 0.3133475976064801
train loss : 0.1855809586122632


 11%|█▏        | 113/1000 [00:00<00:11, 77.65it/s]

train loss : 0.11225068662315607
train loss : 0.07239036168903112
train loss : 0.05350707611069083


 14%|█▍        | 141/1000 [00:01<00:08, 99.42it/s]

train loss : 0.041604479076340795
train loss : 0.03251015627756715
train loss : 0.026625313796103


 17%|█▋        | 169/1000 [00:01<00:07, 115.49it/s]

train loss : 0.021834249040693976
train loss : 0.01732347154757008
train loss : 0.012390780728310347


 20%|█▉        | 197/1000 [00:01<00:06, 126.02it/s]

train loss : 0.008170900997356512
train loss : 0.004611108950484777
train loss : 0.002406575862551108


 23%|██▎       | 226/1000 [00:01<00:05, 132.30it/s]

train loss : 0.0012365480979497079
train loss : 0.0006824584779678844
train loss : 0.0004372729363240069


 27%|██▋       | 268/1000 [00:02<00:05, 135.66it/s]

train loss : 0.0002965803214465268
train loss : 0.0001962164928954735
train loss : 0.00011954138335568132


 30%|██▉       | 296/1000 [00:02<00:05, 136.45it/s]

train loss : 8.506111998940469e-05
train loss : 7.841648130124668e-05
train loss : 7.77360905885871e-05


 32%|███▏      | 324/1000 [00:02<00:04, 136.19it/s]

train loss : 6.953189586056396e-05
train loss : 5.399462725108606e-05
train loss : 3.643244531303935e-05


 35%|███▌      | 352/1000 [00:02<00:04, 134.93it/s]

train loss : 2.2279757331489236e-05
train loss : 1.2562471056298818e-05
train loss : 7.101736628101207e-06


 38%|███▊      | 380/1000 [00:02<00:04, 134.81it/s]

train loss : 4.233833863054315e-06
train loss : 2.811646822920011e-06
train loss : 1.9540538573892263e-06


 41%|████      | 408/1000 [00:03<00:04, 134.21it/s]

train loss : 1.469623938987752e-06
train loss : 1.024100129143335e-06
train loss : 6.401855614512897e-07


 44%|████▎     | 436/1000 [00:03<00:04, 135.16it/s]

train loss : 3.823562018112625e-07
train loss : 2.1000762018275054e-07
train loss : 1.1490483942111496e-07


 48%|████▊     | 478/1000 [00:03<00:03, 135.51it/s]

train loss : 6.572712551999871e-08
train loss : 3.8814379044183056e-08
train loss : 2.4226982420216814e-08


 51%|█████     | 506/1000 [00:03<00:03, 135.97it/s]

train loss : 1.442998481815394e-08
train loss : 8.334591010406012e-09
train loss : 4.486137516589855e-09


 53%|█████▎    | 534/1000 [00:04<00:03, 135.79it/s]

train loss : 2.1811603911903177e-09
train loss : 1.088750728461818e-09
train loss : 5.752366707967305e-10


 56%|█████▌    | 562/1000 [00:04<00:03, 135.64it/s]

train loss : 3.2957695947355425e-10
train loss : 2.0860861649207862e-10
train loss : 1.0986518118871746e-10


 59%|█████▉    | 590/1000 [00:04<00:03, 135.80it/s]

train loss : 5.971423182316027e-11
train loss : 2.985253537424182e-11
train loss : 1.6283311938397604e-11


 62%|██████▏   | 618/1000 [00:04<00:02, 135.97it/s]

train loss : 8.827681288866782e-12
train loss : 5.099527137369941e-12
train loss : 3.7912942099996294e-12


 65%|██████▍   | 646/1000 [00:04<00:02, 135.53it/s]

train loss : 2.5512886074607888e-12
train loss : 1.797927258462284e-12
train loss : 1.4753010553654466e-12


 67%|██████▋   | 674/1000 [00:05<00:02, 134.61it/s]

train loss : 9.671680367391924e-13
train loss : 7.563605435869335e-13
train loss : 5.850686756359198e-13


 72%|███████▏  | 716/1000 [00:05<00:02, 135.46it/s]

train loss : 5.088761782291208e-13
train loss : 4.4163775419917353e-13
train loss : 4.2045890152799664e-13


 74%|███████▍  | 744/1000 [00:05<00:01, 135.91it/s]

train loss : 3.279639099629684e-13
train loss : 2.472483226864013e-13
train loss : 2.588846360050169e-13


 77%|███████▋  | 772/1000 [00:05<00:01, 135.77it/s]

train loss : 1.731082996132144e-13
train loss : 1.4857678804581836e-13
train loss : 1.1474972685108272e-13


 80%|████████  | 800/1000 [00:05<00:01, 135.74it/s]

train loss : 9.574355773532637e-14
train loss : 9.793889179878943e-14
train loss : 6.186719498789579e-14


 83%|████████▎ | 828/1000 [00:06<00:01, 135.58it/s]

train loss : 8.276339276457392e-14
train loss : 8.006122637272588e-14
train loss : 3.66603103291547e-14


 86%|████████▌ | 856/1000 [00:06<00:01, 135.76it/s]

train loss : 3.8458653099841017e-14
train loss : 1.9437952683888264e-14
train loss : 1.9396348807799297e-14


 90%|████████▉ | 898/1000 [00:06<00:00, 135.71it/s]

train loss : 1.654359317958435e-14
train loss : 9.607481858318191e-15
train loss : 1.3880744799833322e-14


 93%|█████████▎| 926/1000 [00:06<00:00, 136.06it/s]

train loss : 9.047841108635412e-15
train loss : 2.0777312467366253e-14
train loss : 2.200393243026249e-14


 95%|█████████▌| 954/1000 [00:07<00:00, 135.45it/s]

train loss : 1.022917401163789e-14
train loss : 1.0195909492551996e-14
train loss : 9.811620702898969e-15


 98%|█████████▊| 982/1000 [00:07<00:00, 135.77it/s]

train loss : 1.0484468884981221e-14
train loss : 4.943593903805543e-15
train loss : 3.046097364992897e-14


100%|██████████| 1000/1000 [00:07<00:00, 134.14it/s]

train loss : 4.760332469228338e-14


gvf_model(
  (fc1): Sequential(
    (0): Linear(in_features=8, out_features=512, bias=True)
    (1): ReLU()
  )
  (fc2): Sequential(
    (0): Linear(in_features=512, out_features=256, bias=True)
    (1): ReLU()
  )
  (fc3): Sequential(
    (0): Linear(in_features=256, out_features=2, bias=True)
  )
)

In [7]:
for i, td in enumerate(dataset):
    test_data = FloatTensor(np.array([td[0]]))
    print(test_data.tolist()[0])
    print(i)
    print(gvf_learner.eval_model(test_data))

[1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0]
0
tensor([[-3.9404e+00,  3.7253e-09]], device='cuda:0', grad_fn=<AddmmBackward>)
[1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0]
1
tensor([[-2.9701e+00,  3.7253e-08]], device='cuda:0', grad_fn=<AddmmBackward>)
[0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0]
2
tensor([[-3.9404e+00, -3.7253e-09]], device='cuda:0', grad_fn=<AddmmBackward>)
[0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0]
3
tensor([[-1.9900e+00,  2.2352e-08]], device='cuda:0', grad_fn=<AddmmBackward>)
[0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0]
4
tensor([[-2.9701e+00,  3.7253e-08]], device='cuda:0', grad_fn=<AddmmBackward>)
[0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0]
5
tensor([[-1.0000e+00, -2.2352e-08]], device='cuda:0', grad_fn=<AddmmBackward>)
[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]
6
tensor([[-3.9404e+00,  1.8626e-08]], device='cuda:0', grad_fn=<AddmmBackward>)
[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]
7
tensor([[-3.9404e+00,  4.8429e-08]], device='cuda:0', grad_fn=<AddmmBackward>)
[0.0, 1.0, 0.0, 0.0, 0.0